server:
  port: 80 # Http 클라이언트 기본 port (명시하지 않아도 된다)
#  forward-headers-strategy: framework # spring request header 전략 설정 native/framework/none

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes: # 어느 경우일 때(predicate) 어디로 보내고(uri) 요청 혹은 응답을 어떻게 할 것인가(filter)
        - id: user-service
#          uri: http://localhost:8091 #최종 요청이 http://localhost:8091/**
          uri: lb://USER # 최종 요청은 서비스 디스커버리에 등록되어 있는 USER-SERVICE로 보내겠다
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user(?<segment>/?.*), /${segment} #요청 경로를 변경하겠다. /user/**를 /**로
        - id: product-service
          uri: http://localhost:8092 #최종 요청이 http://localhost:8092/**
          predicates:
            - Path=/product/**
          filters:
            - RewritePath=/product(?<segment>/?.*), /${segment}